### ISSUE TITLE
Sorting the recovery stats in decreasing order.

### ISSUE THREAD

**Issue by mukundtheamateur** [Nikzy7/india-recovers#4]
How can I sort the recovery stats, I tried using selection sort but it didn't work.

**Comment by Nikzy7** [comment]
The data is dynamic (i.e. pulled from a third party), if you store it in a DS and apply any kind of DS operation it you are basically losing time. Also data on the page is updated via a promise.

**Comment by mukundtheamateur** [comment]
okay
